# Generated by Django 4.2 on 2024-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('percentage_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleAskedForDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('percentage_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('percentage_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchesAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('percentage_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVisitsFromProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('percentage_change', models.IntegerField(default=0)),
            ],
        ),
    ]
